version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  app:
    container_name: app
    build: .
    command: uvicorn fastapi_app:fastapi_app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - redis
  celery_worker:
    container_name: celery_worker
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/1
    build: .
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
      - app
  flower:
    container_name: flower
    build: .
    command: celery -A celery_app flower --port=5555
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - CELERY_RESULT_BACKEND=redis://redis/1
    ports:
      - 5556:5555
    depends_on:
      - app
      - redis
      - celery_worker
